In [111]:
import scipy
from numba import prange, njit

In [21]:
m = 2
n = 3

In [56]:
mat = scipy.sparse.random(n,n,density=0.4,format='csr')

In [106]:
w = np.random.random((n,n))
out = np.zeros((n,n))

In [112]:
def saxpy(off):
off = 2 
for i in range(mat.shape[0]):
    for p in range(mat.indptr[i],mat.indptr[i+1]):
        out.flat[i*n+off] += mat.data[p] * w.flat[mat.indices[p]*n+off]

In [113]:
mat.dot(w)

array([[0.30238737, 0.03579332, 0.35729809],
       [0.72039304, 0.75477851, 0.03296011],
       [0.81822285, 0.56249392, 0.39771185]])

In [114]:
out

array([[0.        , 0.03579332, 0.35729809],
       [0.        , 0.75477851, 0.03296011],
       [0.        , 0.56249392, 0.39771185]])

In [3]:
A = np.random.random((n,n))
W = np.random.random((n,n))

In [15]:
A.dot(W)

array([[0.56591159, 0.96292159, 0.58831383],
       [0.50516528, 1.05025993, 0.91070095],
       [0.20082266, 0.37578242, 0.30403442]])

In [16]:
A.copy().dot(W.flat[::n])

array([0.56591159, 0.50516528, 0.20082266])

In [18]:
W.data.strides

(24, 8)

In [19]:
W.data.strides

(24, 8)